package org.hisp.dhis.sm.action;

import org.hisp.dhis.common.DeleteNotAllowedException;
import org.hisp.dhis.dxf2.sm.api.SynchInstanceService;
import org.hisp.dhis.i18n.I18n;

import com.opensymphony.xwork2.Action;

public class DeleteInstanceAction implements Action
{

    // -------------------------------------------------------------------------
    // Dependencies
    // -------------------------------------------------------------------------
    private SynchInstanceService synchInstanceService;

    public void setSynchInstanceService( SynchInstanceService synchInstanceService )
    {
        this.synchInstanceService = synchInstanceService;
    }

    // -------------------------------------------------------------------------
    // Getters & setters
    // -------------------------------------------------------------------------

    private Integer id;

    public void setId( Integer id )
    {
        this.id = id;
    }

    private String message;

    public String getMessage()
    {
        return message;
    }

    // -------------------------------------------------------------------------
    // I18n
    // -------------------------------------------------------------------------

    private I18n i18n;

    public void setI18n( I18n i18n )
    {
        this.i18n = i18n;
    }

    // -------------------------------------------------------------------------
    // Action
    // -------------------------------------------------------------------------

    public String execute()
        throws Exception
    {
        try
        {
            synchInstanceService.deleteInstance( synchInstanceService.getInstance( id ) );

            message = i18n.getString( "delete_success" );
        }
        catch ( DeleteNotAllowedException ex )
        {
            if ( ex.getErrorCode().equals( DeleteNotAllowedException.ERROR_ASSOCIATED_BY_OTHER_OBJECTS ) )
            {
                message = i18n.getString( "object_not_deleted_associated_by_objects" ) + " " + ex.getMessage();

                return ERROR;
            }
        }
        catch( Exception e )
        {
            message = e.getMessage();
            
            return ERROR;
        }

        return SUCCESS;
    }
}
